/**
 * This code was generated by Diez version 10.2.0.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */
import { Color, File, Font, Image, Typograph } from "@diez/prefabs";

const brandColors = {
    grayscaleGrayDark: Color.rgba(87, 91, 95, 1),
    grayscaleGray: Color.rgba(143, 143, 149, 1),
    grayscaleGrayLight: Color.rgba(221, 221, 222, 1),
    colorYellow: Color.rgba(255, 222, 82, 1)
};

export const brandFonts = {
    SfProText: {
        Regular: Font.fromFile("assets/Brand.figma.contents/fonts/SFProText-Regular.otf"),
        Semibold: Font.fromFile("assets/Brand.figma.contents/fonts/SFProText-Semibold.otf")
    }
};

const brandTypography = {
    headingLarge: new Typograph({ fontSize: 25, color: Color.rgba(0, 0, 0, 1), font: brandFonts.SfProText.Regular }),
    body: new Typograph({ fontSize: 16, color: Color.rgba(87, 91, 95, 1), font: brandFonts.SfProText.Regular }),
    subheading: new Typograph({ fontSize: 13, color: Color.rgba(143, 143, 149, 1), font: brandFonts.SfProText.Semibold })
};

export const brandComponentsFiles = {
    wordmarkSolid: new File({ src: "assets/Brand.figma.contents/components/WordmarkSolid.png" }),
    wordmarkSolid2x: new File({ src: "assets/Brand.figma.contents/components/WordmarkSolid@2x.png" }),
    wordmarkSolid3x: new File({ src: "assets/Brand.figma.contents/components/WordmarkSolid@3x.png" }),
    wordmarkSolid4x: new File({ src: "assets/Brand.figma.contents/components/WordmarkSolid@4x.png" }),
    wordmarkBrand: new File({ src: "assets/Brand.figma.contents/components/WordmarkBrand.png" }),
    wordmarkBrand2x: new File({ src: "assets/Brand.figma.contents/components/WordmarkBrand@2x.png" }),
    wordmarkBrand3x: new File({ src: "assets/Brand.figma.contents/components/WordmarkBrand@3x.png" }),
    wordmarkBrand4x: new File({ src: "assets/Brand.figma.contents/components/WordmarkBrand@4x.png" }),
    componentLabel: new File({ src: "assets/Brand.figma.contents/components/ComponentLabel.png" }),
    componentLabel2x: new File({ src: "assets/Brand.figma.contents/components/ComponentLabel@2x.png" }),
    componentLabel3x: new File({ src: "assets/Brand.figma.contents/components/ComponentLabel@3x.png" }),
    componentLabel4x: new File({ src: "assets/Brand.figma.contents/components/ComponentLabel@4x.png" }),
    cover: new File({ src: "assets/Brand.figma.contents/components/Cover.png" }),
    cover2x: new File({ src: "assets/Brand.figma.contents/components/Cover@2x.png" }),
    cover3x: new File({ src: "assets/Brand.figma.contents/components/Cover@3x.png" }),
    cover4x: new File({ src: "assets/Brand.figma.contents/components/Cover@4x.png" })
};

export const brandComponents = {
    wordmarkSolid: Image.responsive("assets/Brand.figma.contents/components/WordmarkSolid.png", 117, 30.82027244567871),
    wordmarkBrand: Image.responsive("assets/Brand.figma.contents/components/WordmarkBrand.png", 117, 31.056297302246094),
    componentLabel: Image.responsive("assets/Brand.figma.contents/components/ComponentLabel.png", 600, 135),
    cover: Image.responsive("assets/Brand.figma.contents/components/Cover.png", 620, 320)
};

export const brandTokens = {
    colors: brandColors,
    typography: brandTypography
};
