version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
    timezone: America/Halifax
  open-pull-requests-limit: 2
  ignore:
  - dependency-name: eslint-config-prettier
    versions:
    - 8.1.0
    - 8.2.0
