/**
 * This code was generated by Diez version 10.3.0.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */
import { Color, File, Font, Image, Typograph } from "@diez/prefabs";

const brandColors = {
    grayscaleGrayDark: Color.rgba(87, 91, 95, 1),
    gray: Color.rgba(143, 143, 149, 1),
    grayLight: Color.rgba(221, 221, 222, 1),
    colorYellow: Color.rgba(255, 222, 82, 1)
};

export const brandFonts = {
    SfProText: {
        Regular: Font.fromFile("assets/Brand.figma.contents/fonts/SFProText-Regular.otf"),
        Semibold: Font.fromFile("assets/Brand.figma.contents/fonts/SFProText-Semibold.otf")
    }
};

const brandTypography = {
    headingLarge: new Typograph({ letterSpacing: -0.3125, fontSize: 25, lineHeight: 29.296875, color: Color.rgba(0, 0, 0, 1), font: brandFonts.SfProText.Regular }),
    body: new Typograph({ letterSpacing: 0, fontSize: 16, lineHeight: 18.75, color: Color.rgba(87, 91, 95, 1), font: brandFonts.SfProText.Regular }),
    subheading: new Typograph({ letterSpacing: 0.39, fontSize: 13, lineHeight: 15.234375, color: Color.rgba(143, 143, 149, 1), font: brandFonts.SfProText.Semibold })
};

export const brandComponentsFiles = {
    logoBlack: new File({ src: "assets/Brand.figma.contents/components/LogoBlack.png" }),
    logoBlack2x: new File({ src: "assets/Brand.figma.contents/components/LogoBlack@2x.png" }),
    logoBlack3x: new File({ src: "assets/Brand.figma.contents/components/LogoBlack@3x.png" }),
    logoBlack4x: new File({ src: "assets/Brand.figma.contents/components/LogoBlack@4x.png" }),
    wordmarkSolidBlack: new File({ src: "assets/Brand.figma.contents/components/WordmarkSolidBlack.png" }),
    wordmarkSolidBlack2x: new File({ src: "assets/Brand.figma.contents/components/WordmarkSolidBlack@2x.png" }),
    wordmarkSolidBlack3x: new File({ src: "assets/Brand.figma.contents/components/WordmarkSolidBlack@3x.png" }),
    wordmarkSolidBlack4x: new File({ src: "assets/Brand.figma.contents/components/WordmarkSolidBlack@4x.png" }),
    logoColor: new File({ src: "assets/Brand.figma.contents/components/LogoColor.png" }),
    logoColor2x: new File({ src: "assets/Brand.figma.contents/components/LogoColor@2x.png" }),
    logoColor3x: new File({ src: "assets/Brand.figma.contents/components/LogoColor@3x.png" }),
    logoColor4x: new File({ src: "assets/Brand.figma.contents/components/LogoColor@4x.png" }),
    wordmarkColorBlack: new File({ src: "assets/Brand.figma.contents/components/WordmarkColorBlack.png" }),
    wordmarkColorBlack2x: new File({ src: "assets/Brand.figma.contents/components/WordmarkColorBlack@2x.png" }),
    wordmarkColorBlack3x: new File({ src: "assets/Brand.figma.contents/components/WordmarkColorBlack@3x.png" }),
    wordmarkColorBlack4x: new File({ src: "assets/Brand.figma.contents/components/WordmarkColorBlack@4x.png" }),
    wordmarkColorWhite: new File({ src: "assets/Brand.figma.contents/components/WordmarkColorWhite.png" }),
    wordmarkColorWhite2x: new File({ src: "assets/Brand.figma.contents/components/WordmarkColorWhite@2x.png" }),
    wordmarkColorWhite3x: new File({ src: "assets/Brand.figma.contents/components/WordmarkColorWhite@3x.png" }),
    wordmarkColorWhite4x: new File({ src: "assets/Brand.figma.contents/components/WordmarkColorWhite@4x.png" }),
    wordmarkSolidWhite: new File({ src: "assets/Brand.figma.contents/components/WordmarkSolidWhite.png" }),
    wordmarkSolidWhite2x: new File({ src: "assets/Brand.figma.contents/components/WordmarkSolidWhite@2x.png" }),
    wordmarkSolidWhite3x: new File({ src: "assets/Brand.figma.contents/components/WordmarkSolidWhite@3x.png" }),
    wordmarkSolidWhite4x: new File({ src: "assets/Brand.figma.contents/components/WordmarkSolidWhite@4x.png" }),
    logoWhite: new File({ src: "assets/Brand.figma.contents/components/LogoWhite.png" }),
    logoWhite2x: new File({ src: "assets/Brand.figma.contents/components/LogoWhite@2x.png" }),
    logoWhite3x: new File({ src: "assets/Brand.figma.contents/components/LogoWhite@3x.png" }),
    logoWhite4x: new File({ src: "assets/Brand.figma.contents/components/LogoWhite@4x.png" }),
    componentLabel: new File({ src: "assets/Brand.figma.contents/components/ComponentLabel.png" }),
    componentLabel2x: new File({ src: "assets/Brand.figma.contents/components/ComponentLabel@2x.png" }),
    componentLabel3x: new File({ src: "assets/Brand.figma.contents/components/ComponentLabel@3x.png" }),
    componentLabel4x: new File({ src: "assets/Brand.figma.contents/components/ComponentLabel@4x.png" }),
    cover: new File({ src: "assets/Brand.figma.contents/components/Cover.png" }),
    cover2x: new File({ src: "assets/Brand.figma.contents/components/Cover@2x.png" }),
    cover3x: new File({ src: "assets/Brand.figma.contents/components/Cover@3x.png" }),
    cover4x: new File({ src: "assets/Brand.figma.contents/components/Cover@4x.png" })
};

export const brandComponents = {
    logoBlack: Image.responsive("assets/Brand.figma.contents/components/LogoBlack.png", 31, 31.148799896240234),
    wordmarkSolidBlack: Image.responsive("assets/Brand.figma.contents/components/WordmarkSolidBlack.png", 117, 30.82027244567871),
    logoColor: Image.responsive("assets/Brand.figma.contents/components/LogoColor.png", 31, 31.46268653869629),
    wordmarkColorBlack: Image.responsive("assets/Brand.figma.contents/components/WordmarkColorBlack.png", 117, 31.056297302246094),
    wordmarkColorWhite: Image.responsive("assets/Brand.figma.contents/components/WordmarkColorWhite.png", 117, 31.056297302246094),
    wordmarkSolidWhite: Image.responsive("assets/Brand.figma.contents/components/WordmarkSolidWhite.png", 117, 30.82027244567871),
    logoWhite: Image.responsive("assets/Brand.figma.contents/components/LogoWhite.png", 31, 31.148799896240234),
    componentLabel: Image.responsive("assets/Brand.figma.contents/components/ComponentLabel.png", 600, 135),
    cover: Image.responsive("assets/Brand.figma.contents/components/Cover.png", 620, 320)
};

export const brandTokens = {
    colors: brandColors,
    typography: brandTypography
};
