/**
 * This code was generated by Diez version 10.2.3.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */
import { Color, File, Font, GradientStop, Image, LinearGradient, Point2D, Typograph } from "@diez/prefabs";

const stylesColors = {
    black: Color.rgba(0, 0, 0, 1),
    white: Color.rgba(255, 255, 255, 1),
    green: Color.rgba(49, 186, 162, 1),
    mutedGreen: Color.rgba(164, 234, 207, 1),
    red: Color.rgba(213, 32, 73, 1),
    mutedRed: Color.rgba(255, 196, 210, 1),
    blue: Color.rgba(30, 80, 218, 1),
    mutedBlue: Color.rgba(221, 233, 254, 1),
    yellow: Color.rgba(255, 222, 82, 1),
    mutedYellow: Color.rgba(255, 242, 185, 1),
    orange: Color.rgba(245, 139, 35, 1),
    mutedOrange: Color.rgba(255, 202, 165, 1),
    purple: Color.rgba(119, 72, 210, 1),
    mutedPurple: Color.rgba(221, 207, 247, 1),
    teal: Color.rgba(16, 181, 208, 1),
    mutedTeal: Color.rgba(192, 238, 246, 1),
    grayLightest: Color.rgba(247, 247, 248, 1),
    grayLighter: Color.rgba(236, 236, 237, 1),
    grayLight: Color.rgba(221, 221, 222, 1),
    gray: Color.rgba(143, 143, 149, 1),
    grayDark: Color.rgba(87, 91, 95, 1),
    grayDarker: Color.rgba(50, 57, 64, 1),
    black1: Color.rgba(0, 0, 0, 1),
    colorYellow: Color.rgba(255, 222, 82, 1)
};

const stylesGradients = {
    gradientGreen: new LinearGradient({ stops: [GradientStop.make(0, Color.rgba(76, 188, 136, 1)), GradientStop.make(1, Color.rgba(50, 157, 209, 1))], start: Point2D.make(0.821016851389819, -0.105676656843359), end: Point2D.make(-0.390336415164722, 0.674996301605858) }),
    gradientBrand: new LinearGradient({ stops: [GradientStop.make(0, Color.rgba(254, 19, 96, 1)), GradientStop.make(0.26458865404129, Color.rgba(129, 78, 174, 1)), GradientStop.make(0.609017670154572, Color.rgba(45, 152, 204, 1)), GradientStop.make(0.728924870491028, Color.rgba(253, 135, 69, 1)), GradientStop.make(1, Color.rgba(253, 201, 53, 1))], start: Point2D.make(1.181249980120726, -8.693732e-9), end: Point2D.make(-0.409674694679825, 0.914285662290109) }),
    gradientGreenMuted: new LinearGradient({ stops: [GradientStop.make(0, Color.rgba(210, 245, 228, 1)), GradientStop.make(1, Color.rgba(213, 241, 255, 1))], start: Point2D.make(0.821016851389819, -0.105676656843359), end: Point2D.make(-0.390336415164722, 0.674996301605858) }),
    gradientBrand1: new LinearGradient({ stops: [GradientStop.make(0, Color.rgba(218, 86, 108, 1)), GradientStop.make(1, Color.rgba(140, 71, 148, 1))], start: Point2D.make(4.377216e-9, 1.000000004377216), end: Point2D.make(1.000000004377216, 4.377216e-9) }),
    gradientBrandMuted: new LinearGradient({ stops: [GradientStop.make(0, Color.rgba(237, 194, 202, 1)), GradientStop.make(1, Color.rgba(227, 207, 229, 1))], start: Point2D.make(4.377216e-9, 1.000000004377216), end: Point2D.make(1.000000004377216, 4.377216e-9) }),
    gradientBlue: new LinearGradient({ stops: [GradientStop.make(0, Color.rgba(50, 157, 209, 1)), GradientStop.make(1, Color.rgba(79, 80, 164, 1))], start: Point2D.make(0.5, -0.5), end: Point2D.make(-0.5, 0.5) }),
    gradientBlueMuted: new LinearGradient({ stops: [GradientStop.make(0, Color.rgba(177, 229, 255, 1)), GradientStop.make(1, Color.rgba(197, 198, 255, 1))], start: Point2D.make(0.5, -0.5), end: Point2D.make(-0.5, 0.5) }),
    gradientYellow: new LinearGradient({ stops: [GradientStop.make(0, Color.rgba(255, 184, 58, 1)), GradientStop.make(1, Color.rgba(255, 226, 104, 1))], start: Point2D.make(0.527897182467498, 1.55579430626508), end: Point2D.make(1.527897158999531, 0.499999988266017) }),
    gradientYellowMuted: new LinearGradient({ stops: [GradientStop.make(0, Color.rgba(255, 217, 149, 1)), GradientStop.make(1, Color.rgba(255, 247, 211, 1))], start: Point2D.make(0.567276093902552, 1.59738067308683), end: Point2D.make(1.650448750489284, 0.46282849512784) }),
    gradientOrange: new LinearGradient({ stops: [GradientStop.make(0, Color.rgba(255, 2, 100, 1)), GradientStop.make(1, Color.rgba(253, 223, 49, 1))], start: Point2D.make(0.322843937601224, 2.070313632698886), end: Point2D.make(1.846504348936375, 0.67485791912246) }),
    gradientOrangeMuted: new LinearGradient({ stops: [GradientStop.make(0, Color.rgba(245, 188, 165, 1)), GradientStop.make(1, Color.rgba(255, 241, 215, 1))], start: Point2D.make(0.53288843739154, 1.755845003537722), end: Point2D.make(1.762725784434706, 0.527946382205596) }),
    gradientPurple: new LinearGradient({ stops: [GradientStop.make(0, Color.rgba(165, 114, 255, 1)), GradientStop.make(1, Color.rgba(84, 62, 221, 1))], start: Point2D.make(0.5, -0.5), end: Point2D.make(-0.5, 0.5) }),
    gradientPurpleMuted: new LinearGradient({ stops: [GradientStop.make(0, Color.rgba(234, 222, 255, 1)), GradientStop.make(1, Color.rgba(203, 195, 255, 1))], start: Point2D.make(0.5, -0.5), end: Point2D.make(-0.5, 0.5) }),
    gradientRed: new LinearGradient({ stops: [GradientStop.make(0, Color.rgba(175, 13, 30, 1)), GradientStop.make(1, Color.rgba(255, 53, 112, 1))], start: Point2D.make(0.5, 1.5), end: Point2D.make(1.5, 0.5) }),
    gradientRedMuted: new LinearGradient({ stops: [GradientStop.make(0, Color.rgba(255, 179, 179, 1)), GradientStop.make(1, Color.rgba(253, 131, 178, 1))], start: Point2D.make(0.5, -0.5), end: Point2D.make(-0.5, 0.5) })
};

export const stylesFonts = {
    SfProText: {
        Regular: Font.fromFile("assets/Styles.figma.contents/fonts/SFProText-Regular.otf"),
        Medium: Font.fromFile("assets/Styles.figma.contents/fonts/SFProText-Medium.otf"),
        Semibold: Font.fromFile("assets/Styles.figma.contents/fonts/SFProText-Semibold.otf"),
        Bold: Font.fromFile("assets/Styles.figma.contents/fonts/SFProText-Bold.otf")
    },
    IbmPlexMono: {
        Regular: Font.fromFile("assets/Styles.figma.contents/fonts/IBMPlexMono.otf")
    }
};

const stylesTypography = {
    caption: new Typograph({ fontSize: 12, color: Color.rgba(0, 0, 0, 1), font: stylesFonts.SfProText.Regular }),
    monoCaption: new Typograph({ fontSize: 10, color: Color.rgba(0, 0, 0, 1), font: stylesFonts.IbmPlexMono.Regular }),
    label: new Typograph({ fontSize: 14, color: Color.rgba(0, 0, 0, 1), font: stylesFonts.SfProText.Regular }),
    monoLabel: new Typograph({ fontSize: 12, color: Color.rgba(0, 0, 0, 1), font: stylesFonts.IbmPlexMono.Regular }),
    body: new Typograph({ fontSize: 16, color: Color.rgba(0, 0, 0, 1), font: stylesFonts.SfProText.Regular }),
    monoBody: new Typograph({ fontSize: 14, color: Color.rgba(0, 0, 0, 1), font: stylesFonts.IbmPlexMono.Regular }),
    subheadingSmall: new Typograph({ fontSize: 11, color: Color.rgba(0, 0, 0, 1), font: stylesFonts.SfProText.Medium }),
    subheading: new Typograph({ fontSize: 13, color: Color.rgba(0, 0, 0, 1), font: stylesFonts.SfProText.Semibold }),
    heading: new Typograph({ fontSize: 20, color: Color.rgba(0, 0, 0, 1), font: stylesFonts.SfProText.Regular }),
    headingLarge: new Typograph({ fontSize: 25, color: Color.rgba(0, 0, 0, 1), font: stylesFonts.SfProText.Regular }),
    headingExtraLarge: new Typograph({ fontSize: 32, color: Color.rgba(0, 0, 0, 1), font: stylesFonts.SfProText.Medium }),
    sidebarBigTitle: new Typograph({ fontSize: 16, color: Color.rgba(0, 0, 0, 1), font: stylesFonts.SfProText.Semibold }),
    sidebarSmallTitle: new Typograph({ fontSize: 14, color: Color.rgba(0, 0, 0, 1), font: stylesFonts.SfProText.Bold }),
    smallScreenCaption: new Typograph({ fontSize: 13, color: Color.rgba(0, 0, 0, 1), font: stylesFonts.SfProText.Regular }),
    smallScreenLabel: new Typograph({ fontSize: 14, color: Color.rgba(0, 0, 0, 1), font: stylesFonts.SfProText.Regular }),
    smallScreenBody: new Typograph({ fontSize: 16, color: Color.rgba(0, 0, 0, 1), font: stylesFonts.SfProText.Regular }),
    smallScreenHeading: new Typograph({ fontSize: 18, color: Color.rgba(0, 0, 0, 1), font: stylesFonts.SfProText.Regular }),
    smallScreenHeadingLarge: new Typograph({ fontSize: 22, color: Color.rgba(0, 0, 0, 1), font: stylesFonts.SfProText.Regular }),
    smallScreenHeadingExtraLarge: new Typograph({ fontSize: 26, color: Color.rgba(0, 0, 0, 1), font: stylesFonts.SfProText.Medium })
};

export const stylesComponentsFiles = {
    swatch: new File({ src: "assets/Styles.figma.contents/components/Swatch.png" }),
    swatch2x: new File({ src: "assets/Styles.figma.contents/components/Swatch@2x.png" }),
    swatch3x: new File({ src: "assets/Styles.figma.contents/components/Swatch@3x.png" }),
    swatch4x: new File({ src: "assets/Styles.figma.contents/components/Swatch@4x.png" })
};

export const stylesComponents = {
    swatch: Image.responsive("assets/Styles.figma.contents/components/Swatch.png", 160, 224)
};

export const stylesTokens = {
    colors: stylesColors,
    gradients: stylesGradients,
    typography: stylesTypography
};
